// <auto-generated />
namespace LocadoraWebApi.Consumo.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class criacaoTabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criacaoTabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "202009132256010_criacaoTabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
